networks:
  todo-network:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    restart: always
    networks:
      - todo-network
    # depends_on:
    #   - database
    # environment:
    #   - MONGODB_URI=mongodb+srv://shyvikas63:shyvikas63@cluster0.2a1gfmc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    # env_file:
    #   - DB.env

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - backend
    networks:
      - todo-network

# # Optional database service
#   database:
#     image: postgres:13
#     restart: always
#     networks:
#       - app-network
#     environment:
#       - POSTGRES_USER=myuser
#       - POSTGRES_PASSWORD=mypassword
#       - POSTGRES_DB=mydb