networks:
  todo-network:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    restart: always
    networks:
      - todo-network
    depends_on:
      - database
    # environment:
    #   - MONGODB_URI=mongodb+srv://shyvikas63:shyvikas63@cluster0.2a1gfmc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    env_file:
      - DB.env

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - backend
    networks:
      - todo-network

  database:
    image: mongo:latest
    restart: always
    networks:
      - todo-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: