name: todo-mern deployed to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose
        run: |
          docker-compose up -d --build

      - name: Verify deployment
        run: |
          docker ps
          echo "Deployment successful!"