name: todo-mern-deployed-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: create DB.env file
        run: |
          echo "$DB_ENV" > DB.env
          echo "DB.env file created successfully!"
          cat DB.env

      - name: Set up Docker Compose
        run: |
            DC_PATH=$(which docker-compose)
            echo "DC_PATH=$DC_PATH" >> $GITHUB_ENV

      - name: Stop and remove existing containers
        run: |
          sudo $DC_PATH down 
          sudo $DC_PATH rm -f

      - name: Deploy using Docker Compose
        run: |
          sudo $DC_PATH up -d --build

      - name: Verify deployment
        run: |
          sudo /usr/bin/docker ps
          echo "Deployment successful!"

      - name: restart nginx
        run: |
          sudo systemctl restart nginx
